Repository lee-ji-an/Algorithm_Study, pull requests merged in 2023-01, with the labels that each got.

#4 week1-PPakSang
  BOJ/BF/1062/PPakSang/Main.java
  BOJ/BF/1062/PPakSang/Main2.java
  BOJ/BF/1062/PPakSang/README.md
  BOJ/BF/1339/PPakSang/Main.java
  BOJ/BF/1339/PPakSang/README.md
  BOJ/BF/13460/PPakSang/Main.java
  BOJ/BF/13460/PPakSang/README.md
  BOJ/BF/14225/PPakSang/Main.java
  BOJ/BF/14225/PPakSang/Main2.java
  BOJ/BF/14225/PPakSang/README.md
  BOJ/BF/14889/PPakSang/Main.java
  BOJ/BF/14889/PPakSang/README.md
  BOJ/BF/2529/PPakSang/Main.java
  BOJ/BF/2529/PPakSang/README.md
Labels: Brute Force, Java

#2 week1-oroko
  BOJ/BF/1062/oroko/P1062.java
  BOJ/BF/1062/oroko/README.md
  BOJ/BF/1339/oroko/P1339.java
  BOJ/BF/1339/oroko/README.md
  BOJ/BF/13460/oroko/P13460.java
  BOJ/BF/13460/oroko/README.md
  BOJ/BF/14225/oroko/P14225.java
  BOJ/BF/14225/oroko/README.md
  BOJ/BF/14889/oroko/P14889.java
  BOJ/BF/14889/oroko/README.md
  BOJ/BF/2529/oroko/P2529.java
  BOJ/BF/2529/oroko/README.md
Labels: Brute Force, Java

#1 week1-hw0603
  BOJ/BF/1062/hw0603/1062.py
  BOJ/BF/1062/hw0603/README.md
  BOJ/BF/12100/hw0603/12100.py
  BOJ/BF/12100/hw0603/README.md
  BOJ/BF/1339/hw0603/1339.py
  BOJ/BF/1339/hw0603/README.md
  BOJ/BF/13460/hw0603/13460.py
  BOJ/BF/13460/hw0603/README.md
  BOJ/BF/14225/hw0603/14225.py
  BOJ/BF/14225/hw0603/README.md
  BOJ/BF/14889/hw0603/14889.py
  BOJ/BF/14889/hw0603/README.md
  BOJ/BF/2529/hw0603/2529.py
  BOJ/BF/2529/hw0603/README.md
Labels: Brute Force, Python

#3 week1-dltmdrl1244
  BOJ/BF/1062/dltmdrl1244/1062.py
  BOJ/BF/1062/dltmdrl1244/README.md
  BOJ/BF/1339/dltmdrl1244/1339.py
  BOJ/BF/1339/dltmdrl1244/README.md
  BOJ/BF/13460/dltmdrl1244/13460.py
  BOJ/BF/13460/dltmdrl1244/README.md
  BOJ/BF/14225/dltmdrl1244/14225.py
  BOJ/BF/14225/dltmdrl1244/README.md
  BOJ/BF/14889/dltmdrl1244/14889.py
  BOJ/BF/14889/dltmdrl1244/README.md
  BOJ/BF/2529/dltmdrl1244/2529.py
  BOJ/BF/2529/dltmdrl1244/README.md
Labels: Brute Force, Python

#5 week1-lee-ji-an
  BOJ/BF/1062/lee-ji-an/1062.py
  BOJ/BF/1062/lee-ji-an/README.md
  BOJ/BF/1339/lee-ji-an/1339.py
  BOJ/BF/1339/lee-ji-an/README.md
  BOJ/BF/13460/lee-ji-an/13460.py
  BOJ/BF/13460/lee-ji-an/README.md
  BOJ/BF/14225/lee-ji-an/14225.py
  BOJ/BF/14225/lee-ji-an/README.md
  BOJ/BF/14889/lee-ji-an/14889.py
  BOJ/BF/14889/lee-ji-an/README.md
  BOJ/BF/2529/lee-ji-an/2529.py
  BOJ/BF/2529/lee-ji-an/README.md
Labels: Brute Force, Python

#10 week2-1_dltmdrl1244
  BOJ/BF/1208/dltmdrl1244/1208.py
  BOJ/BF/1208/dltmdrl1244/README.md
  BOJ/BF/12100/dltmdrl1244/12100.py
  BOJ/BF/12100/dltmdrl1244/README.md
  BOJ/BF/1644/dltmdrl1244/1644.py
  BOJ/BF/1644/dltmdrl1244/README.md
  BOJ/BF/1806/dltmdrl1244/1806.py
  BOJ/BF/1806/dltmdrl1244/README.md
  BOJ/BF/2003/dltmdrl1244/2003.py
  BOJ/BF/2003/dltmdrl1244/README.md
  BOJ/BF/2143/dltmdrl1244/2143.py
  BOJ/BF/2143/dltmdrl1244/README.md
Labels: Brute Force, Python

#11 week2-1_oroko
  BOJ/BF/1208/oroko/P1208.java
  BOJ/BF/1208/oroko/README.md
  BOJ/BF/12100/oroko/P12100.java
  BOJ/BF/12100/oroko/README.md
  BOJ/BF/14888/oroko/P14888.java
  BOJ/BF/14888/oroko/README.md
  BOJ/BF/1644/oroko/P1644.java
  BOJ/BF/1644/oroko/README.md
  BOJ/BF/1806/oroko/P1206.java
  BOJ/BF/1806/oroko/README.md
  BOJ/BF/2003/oroko/P2003.java
  BOJ/BF/2003/oroko/README.md
  BOJ/BF/2143/oroko/P2143.java
  BOJ/BF/2143/oroko/README.md
Labels: Brute Force, Java

#6 week2-1_hw0603
  .gitignore
  BOJ/BF/1644/hw0603/1644.py
  BOJ/BF/1644/hw0603/README.md
  BOJ/BF/1806/hw0603/1806.py
  BOJ/BF/1806/hw0603/README.md
  BOJ/BF/2003/hw0603/2003.py
  BOJ/BF/2003/hw0603/README.md
  BOJ/BF/2143/hw0603/2143.py
  BOJ/BF/2143/hw0603/README.md
Labels: Brute Force, Python

#8 week2-1_PPakSang
  BOJ/BF/1806/PPakSang/Main.java
  BOJ/BF/1806/PPakSang/README.md
  BOJ/BF/2003/PPakSang/Main.java
  BOJ/BF/2003/PPakSang/README.md
  BOJ/BF/2143/PPakSang/Main.java
  BOJ/BF/2143/PPakSang/README.md
Labels: Brute Force, Java

#9 week2-1_lee-ji-an
  BOJ/BF/1806/lee-ji-an/1806.py
  BOJ/BF/1806/lee-ji-an/README.md
  BOJ/BF/2003/lee-ji-an/2003.py
  BOJ/BF/2003/lee-ji-an/README.md
  BOJ/BF/2143/lee-ji-an/2143.py
  BOJ/BF/2143/lee-ji-an/README.md
Labels: Brute Force, Python

#14 week3-1_lee-ji-an
  BOJ/BF/16929/lee-ji-an/16929.py
  BOJ/BF/16929/lee-ji-an/README.md
  BOJ/BF/16947/lee-ji-an/16947.py
  BOJ/BF/16947/lee-ji-an/README.md
  BOJ/BF/16964/lee-ji-an/16964.py
  BOJ/BF/16964/lee-ji-an/README.md
Labels: Graph Traversal, Python

#13 week3-1_PPakSang
  BOJ/BF/16929/PPakSang/Main.java
  BOJ/BF/16929/PPakSang/README.md
  BOJ/BF/16947/PPakSang/Main.java
  BOJ/BF/16947/PPakSang/Main2.java
  BOJ/BF/16947/PPakSang/README.md
  BOJ/BF/16964/PPakSang/Main.java
  BOJ/BF/16964/PPakSang/README.md
Labels: Graph Traversal, Java

#12 week3-1_hw0603
  .gitignore
  BOJ/BF/16929/hw0603/16929.py
  BOJ/BF/16929/hw0603/16929_old.py
  BOJ/BF/16929/hw0603/README.md
  BOJ/BF/16947/hw0603/16947.py
  BOJ/BF/16947/hw0603/README.md
  BOJ/BF/16964/hw0603/16964.py
  BOJ/BF/16964/hw0603/README.md
Labels: Graph Traversal, Python

#16 week3-1_oroko
  BOJ/BF/12946/oroko/P12946.java
  BOJ/BF/12946/oroko/README.md
  BOJ/BF/16929/oroko/P16929.java
  BOJ/BF/16929/oroko/README.md
  BOJ/BF/16947/oroko/P16947.java
  BOJ/BF/16947/oroko/README.md
Labels: Graph Traversal, Java

#15 week3-1_dltmdrl1244
  BOJ/BF/16929/dltmdrl1244/16929.py
  BOJ/BF/16929/dltmdrl1244/README.md
  BOJ/BF/16940/dltmdrl1244/16940.py
  BOJ/BF/16940/dltmdrl1244/README.md
  BOJ/BF/16947/dltmdrl1244/16947.py
  BOJ/BF/16947/dltmdrl1244/README.md
  BOJ/BF/16964/dltmdrl1244/16964.py
  BOJ/BF/16964/dltmdrl1244/README.md
Labels: Graph Traversal, Python

#19 week3-2_oroko
  BOJ/BFS/12886/oroko/P12886.java
  BOJ/BFS/12886/oroko/README.md
  BOJ/BFS/14442/oroko/P14442.java
  BOJ/BFS/14442/oroko/README.md
  BOJ/BFS/14502/oroko/P14502.java
  BOJ/BFS/14502/oroko/README.md
  BOJ/BFS/16928/oroko/P16928.java
  BOJ/BFS/16928/oroko/README.md
  BOJ/BFS/2206/oroko/P2206.java
  BOJ/BFS/2206/oroko/README.md
Labels: Graph Traversal, Java

#18 week3-2_PPakSang
  BOJ/BFS/14502/PPakSang/Main.java
  BOJ/BFS/14502/PPakSang/README.md
  BOJ/BFS/16928/PPakSang/Main.java
  BOJ/BFS/16928/PPakSang/README.md
  BOJ/BFS/2206/PPakSang/Main.java
  BOJ/BFS/2206/PPakSang/README.md
Labels: Graph Traversal, Java

#20 week3-2_dltmdrl1244
  BOJ/BFS/12886/dltmdrl1244/12886.py
  BOJ/BFS/12886/dltmdrl1244/README.md
  BOJ/BFS/14442/dltmdrl1244/14442.py
  BOJ/BFS/14442/dltmdrl1244/README.md
  BOJ/BFS/14502/dltmdrl1244/14502.py
  BOJ/BFS/14502/dltmdrl1244/14502_2.py
  BOJ/BFS/14502/dltmdrl1244/README.md
  BOJ/BFS/16928/dltmdrl1244/16928.py
  BOJ/BFS/16928/dltmdrl1244/README.md
  BOJ/BFS/2206/dltmdrl1244/2206.py
  BOJ/BFS/2206/dltmdrl1244/README.md
Labels: Graph Traversal, Python

#22 week4_hw0603
  BOJ/BFS/16236/hw0603/16236.py
  BOJ/BFS/16236/hw0603/README.md
  BOJ/BFS/16933/hw0603/16933.py
  BOJ/BFS/16933/hw0603/README.md
  BOJ/BFS/16946/hw0603/16946.py
  BOJ/BFS/16946/hw0603/README.md
  BOJ/BFS/16948/hw0603/16948.py
  BOJ/BFS/16948/hw0603/README.md
  BOJ/BFS/16954/hw0603/16954.py
  BOJ/BFS/16954/hw0603/README.md
  BOJ/BFS/1963/hw0603/1963.py
  BOJ/BFS/1963/hw0603/README.md
  BOJ/BFS/6087/hw0603/6087.py
  BOJ/BFS/6087/hw0603/README.md
Labels: Graph Traversal, Python

#26 week4_oroko
  BOJ/BFS/16236/oroko/P16236.java
  BOJ/BFS/16236/oroko/README.md
  BOJ/BFS/16948/oroko/P16948.java
  BOJ/BFS/16948/oroko/README.md
  BOJ/BFS/16954/oroko/P16954.java
  BOJ/BFS/16954/oroko/README.md
  BOJ/BFS/1963/oroko/P1963.java
  BOJ/BFS/1963/oroko/README.md
  BOJ/BFS/6087/oroko/P6087.java
  BOJ/BFS/6087/oroko/README.md
Labels: Graph Traversal, Java

#24 week4_PPakSang
  BOJ/BFS/16236/PPakSang/Main.java
  BOJ/BFS/16236/PPakSang/README.md
  BOJ/BFS/16933/PPakSang/Main.java
  BOJ/BFS/16933/PPakSang/README.md
  BOJ/BFS/16946/PPakSang/Main.java
  BOJ/BFS/16946/PPakSang/README.md
  BOJ/BFS/16954/PPakSang/Main.java
  BOJ/BFS/16954/PPakSang/README.md
  BOJ/BFS/1963/PPakSang/Main.java
  BOJ/BFS/1963/PPakSang/README.md
  BOJ/BFS/6087/PPakSang/Main.java
  BOJ/BFS/6087/PPakSang/README.md
Labels: Graph Traversal, Java

#23 week4_dltmdrl1244
  BOJ/BF/12946/dltmdrl1244/12946.py
  BOJ/BF/12946/dltmdrl1244/README.md
  BOJ/BFS/10026/dltmdrl1244/10026.py
  BOJ/BFS/10026/dltmdrl1244/README.md
  BOJ/BFS/14395/dltmdrl1244/14395.py
  BOJ/BFS/14395/dltmdrl1244/README.md
  BOJ/BFS/16236/dltmdrl1244/16236.py
  BOJ/BFS/16236/dltmdrl1244/README.md
  BOJ/BFS/16933/dltmdrl1244/16933.py
  BOJ/BFS/16933/dltmdrl1244/README.md
  BOJ/BFS/16946/dltmdrl1244/16946.py
  BOJ/BFS/16946/dltmdrl1244/README.md
  BOJ/BFS/16948/dltmdrl1244/16948.py
  BOJ/BFS/16948/dltmdrl1244/README.md
  BOJ/BFS/16954/dltmdrl1244/16954.py
  BOJ/BFS/16954/dltmdrl1244/README.md
  BOJ/BFS/1963/dltmdrl1244/1963.py
  BOJ/BFS/1963/dltmdrl1244/README.md
  BOJ/BFS/5014/dltmdrl1244/5014.py
  BOJ/BFS/5014/dltmdrl1244/README.md
  BOJ/BFS/6087/dltmdrl1244/6087.py
  BOJ/BFS/6087/dltmdrl1244/README.md
Labels: Graph Traversal, Python

#25 week4_lee-ji-an
  BOJ/BFS/16236/lee-ji-an/16236.py
  BOJ/BFS/16236/lee-ji-an/README.md
  BOJ/BFS/16933/lee-ji-an/16933.py
  BOJ/BFS/16933/lee-ji-an/README.md
  BOJ/BFS/16946/lee-ji-an/16946.py
  BOJ/BFS/16946/lee-ji-an/README.md
  BOJ/BFS/16948/lee-ji-an/16948.py
  BOJ/BFS/16948/lee-ji-an/README.md
  BOJ/BFS/16954/lee-ji-an/16954.py
  BOJ/BFS/16954/lee-ji-an/README.md
  BOJ/BFS/1963/lee-ji-an/1963.py
  BOJ/BFS/1963/lee-ji-an/README.md
  BOJ/BFS/6087/lee-ji-an/6087.py
  BOJ/BFS/6087/lee-ji-an/README.md
Labels: Graph Traversal, Python

#28 week4_dntmdxor99
  BOJ/BFS/10026/dntmdxor99/10026.py
  BOJ/BFS/14395/dntmdxor99/14395.py
  BOJ/BFS/16236/dntmdxor99/16236.py
  BOJ/BFS/16928/dntmdxor99/16928.py
  BOJ/BFS/16933/dntmdxor99/16933.py
  BOJ/BFS/16946/dntmdxor99/16946.py
  BOJ/BFS/16948/dntmdxor99/16948.py
  BOJ/BFS/16954/dntmdxor99/16954.py
  BOJ/BFS/1963/dntmdxor99/1963.py
  BOJ/BFS/5014/dntmdxor99/5014.py
  BOJ/BFS/6087/dntmdxor99/6087.py
Labels: Graph Traversal, Python

#33 week5-1_oroko
  BOJ/BFS/1600/oroko/P1600.java
  BOJ/BFS/1600/oroko/README.md
  BOJ/BFS/17086/oroko/P17086.java
  BOJ/BFS/17086/oroko/README.md
  BOJ/BFS/17141/oroko/P17142.java
  BOJ/BFS/17141/oroko/README.md
  BOJ/BFS/4991/oroko/P4991.java
  BOJ/BFS/4991/oroko/README.md
Labels: Graph Traversal, Java

#34 week5-1_lee-ji-an
  BOJ/BFS/1600/lee-ji-an/1600.py
  BOJ/BFS/1600/lee-ji-an/README.md
  BOJ/BFS/17086/lee-ji-an/17086.py
  BOJ/BFS/17086/lee-ji-an/README.md
  BOJ/BFS/17141/lee-ji-an/17141.py
  BOJ/BFS/17141/lee-ji-an/README.md
  BOJ/BFS/4991/lee-ji-an/4991.py
  BOJ/BFS/4991/lee-ji-an/README.md
Labels: Graph Traversal, Python

#32 week5-1_dltmdrl1244
  BOJ/BFS/1600/dltmdrl1244/1600.py
  BOJ/BFS/1600/dltmdrl1244/README.md
  BOJ/BFS/17086/dltmdrl1244/17086.py
  BOJ/BFS/17086/dltmdrl1244/README.md
  BOJ/BFS/17141/dltmdrl1244/17141.py
  BOJ/BFS/17141/dltmdrl1244/README.md
  BOJ/BFS/4991/dltmdrl1244/4991.py
  BOJ/BFS/4991/dltmdrl1244/4991_2.py
  BOJ/BFS/4991/dltmdrl1244/README.md
  BOJ/BFS/6087/dltmdrl1244/6087.py
  BOJ/BFS/6087/dltmdrl1244/6087_1.py
Labels: Graph Traversal, Python

#31 week5-1_PPakSang
  BOJ/BFS/1600/PPakSang/Main.java
  BOJ/BFS/1600/PPakSang/README.md
  BOJ/BFS/17086/PPakSang/Main.java
  BOJ/BFS/17086/PPakSang/README.md
  BOJ/BFS/17141/PPakSang/Main.java
  BOJ/BFS/17141/PPakSang/README.md
  BOJ/BFS/4991/PPakSang/Main.java
  BOJ/BFS/4991/PPakSang/README.md
Labels: Graph Traversal, Java

#29 week5-1_hw0603
  BOJ/BFS/1600/hw0603/1600.py
  BOJ/BFS/1600/hw0603/README.md
  BOJ/BFS/17086/hw0603/17086.py
  BOJ/BFS/17086/hw0603/README.md
  BOJ/BFS/17141/hw0603/17141.py
  BOJ/BFS/17141/hw0603/README.md
  BOJ/BFS/4991/hw0603/4991.py
  BOJ/BFS/4991/hw0603/README.md
Labels: Graph Traversal, Python
